name: kuwboo
repository: https://github.com/pcutting/team_kuwboo_flutter

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze --fatal-infos
    exec:
      concurrency: 5

  format:
    run: dart format --set-exit-if-changed .

  build:web:
    run: flutter build web --release
    packageFilters:
      dirExists: web
