export enum ConsentType {
  TERMS = 'TERMS',
  PRIVACY = 'PRIVACY',
  MARKETING = 'MARKETING',
  LOCATION = 'LOCATION',
  COOKIES = 'COOKIES',
  DATA_SALE_OPT_OUT = 'DATA_SALE_OPT_OUT',
}

export enum ConsentSource {
  REGISTRATION = 'REGISTRATION',
  SETTINGS = 'SETTINGS',
  PROMPT = 'PROMPT',
  LEGAL_UPDATE = 'LEGAL_UPDATE',
}
